### ISSUE TITLE
Simulate a connection to real device driver?

### ISSUE THREAD

**Issue by mikedorin** [sysprog21/vwifi#28]
I would like to test the internals of a real device driver for an AP against a large collection of simulated stations.
My idea would be to cut off the RF portions of the real AP and connect to your simulated RF transport. 
Does this behave enough like true linux wifi that this could work? If I got the simulated RF correct, the AP would think it was connected to many stations?

Thank you! 
Mike

**Comment by jserv** [comment]
@mikedorin, You can try [virt_wifi](https://github.com/torvalds/linux/blob/master/drivers/net/wireless/virt_wifi.c), a fake implementation of `cfg80211_ops` that can be tacked on to an ethernet `net_device` to make it appear as a wireless connection.
