### ISSUE TITLE
Enforce more consistent naming scheme

### ISSUE THREAD

**Issue by jserv** [sysprog21/vwifi#52]
Currently, various functions in our project start with the prefix "owl," an acronym for "Our WirelessLan." However, this naming convention is no longer relevant since the project has been renamed to `vwifi`, representing virtual WiFi. To maintain consistency and clarity in our codebase, it is necessary to update the naming scheme for all symbols used in this project. Therefore, I propose that we transition to using the prefix "vwifi" instead of "owl" for all relevant functions and symbols.

Similarly, the network interface names created by the vwifi kernel module can follow the format "vw0", "vw1", and so on.

**Comment by vax-r** [comment]
Is this issue still available ? if so , I would like to help.
Btw, change `owl` to `vw` or change `owl` to `vwifi` ?
Which one is more preferred?

**Comment by jserv** [comment]
> Is this issue still available ? if so , I would like to help. Btw, change `owl` to `vw` or change `owl` to `vwifi` ? Which one is more preferred?

Progress on this issue was stalled due to @rickywu0421's commitment to military service.
It is supposed that `vwifi_` is enforced to be the prefix for functions or related identifiers. `vw` is used for the interface names, such as `vw0` and `vw1`.
