### ISSUE TITLE
make[1]: *** No rule to make target 'modules' .Stop

### ISSUE THREAD

**Issue by Texmozito** [sysprog21/vwifi#60]
Hello there, I was trying to build the vwifi myself until I found this error: 

make -C /lib/modules/6.1.84-1-MANJARO/build M=/home/texmoz/aur/vwifi modules
make[1]: se entra en el directorio '/usr/lib/modules/6.1.84-1-MANJARO/build'
make[1]: *** No hay ninguna regla para construir el objetivo 'modules'.  Alto.
make[1]: se sale del directorio '/usr/lib/modules/6.1.84-1-MANJARO/build'
make: *** [Makefile:11: kmod] Error 2

As "Texmoz" is my user name and I'm using that kernel, I thank any kind of solution.

Pd, if language gives any trouble, let me know and I'll try to change the language.

**Comment by jserv** [comment]
Can you build some of the Linux kernel modules listed in [LKMPG](https://sysprog21.github.io/lkmpg/)?

**Comment by Texmozito** [comment]
How can I do that?

**Comment by jserv** [comment]
> How can I do that?

Simply read [LKMPG](https://sysprog21.github.io/lkmpg/) and attempt to build some of the available Linux kernel modules.
I am the editor of LKMPG.

**Comment by Texmozito** [comment]
I tried to build this one "4.1 The Simplest Module", and I've got se same result as the issue I've opened, any suggestions?

**Comment by jserv** [comment]
> I tried to build this one "4.1 The Simplest Module", and I've got se same result as the issue I've opened, any suggestions?

It implies that you should check the installation of kernel header packages.

**Comment by Texmozito** [comment]
Thank you so much, I had this issue for days
